# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_shop"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = "2012-02-16"
  s.files = [
    "app/assets/javascripts/cart.js",
    "app/assets/javascripts/carts.js",
    "app/assets/javascripts/spud/admin/products.js",
    "app/assets/javascripts/spud/admin/users.js",
    "app/assets/javascripts/spud/user_sessions.js",
    "app/assets/stylesheets/cart.css",
    "app/assets/stylesheets/carts.css",
    "app/assets/stylesheets/spud/admin/products.css",
    "app/controllers/carts_controller.rb",
    "app/controllers/spud/admin/products_controller.rb",
    "app/helpers/cart_helper.rb",
    "app/helpers/carts_helper.rb",
    "app/helpers/spud/admin/products_helper.rb",
    "app/helpers/spud/admin/users_helper.rb",
    "app/helpers/spud/user_sessions_helper.rb",
    "app/models/spud_cart.rb",
    "app/models/spud_cart_item.rb",
    "app/models/spud_order.rb",
    "app/models/spud_product.rb",
    "app/models/spud_product_price.rb",
    "app/views/carts/checkout.html.erb",
    "app/views/carts/show.html.erb",
    "app/views/spud/admin/products/_form.html.erb",
    "app/views/spud/admin/products/edit.html.erb",
    "app/views/spud/admin/products/index.html.erb",
    "app/views/spud/admin/products/new.html.erb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_shop.rb",
    "lib/spud_shop/configuration.rb",
    "lib/spud_shop/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Spud Shop Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spud_core>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<activemerchant>, [">= 0"])
      s.add_runtime_dependency(%q<active_shipping>, [">= 0"])
    else
      s.add_dependency(%q<spud_core>, [">= 0.5.0"])
      s.add_dependency(%q<activemerchant>, [">= 0"])
      s.add_dependency(%q<active_shipping>, [">= 0"])
    end
  else
    s.add_dependency(%q<spud_core>, [">= 0.5.0"])
    s.add_dependency(%q<activemerchant>, [">= 0"])
    s.add_dependency(%q<active_shipping>, [">= 0"])
  end
end

